### ISSUE TITLE
Rubocop 0.34 is breaking style tests

### ISSUE THREAD

**Issue by kons4349** [rackspace-cookbooks/rackspace_nginx_php#10]
```
bundle exec rake style
warning: parser/current is loading parser/ruby21, which recognizes
warning: 2.1.6-compliant syntax, but you are running 2.1.5.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Running RuboCop...
undefined method `map' for nil:NilClass
/home/ubuntu/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych.rb:287:in `safe_load'
/home/ubuntu/bundle/ruby/2.1.0/gems/rubocop-0.34.0/lib/rubocop/config_loader.rb:151:in `yaml_safe_load'
/home/ubuntu/bundle/ruby/2.1.0/gems/rubocop-0.34.0/lib/rubocop/config_loader.rb:138:in `load_yaml_configuration'
/home/ubuntu/bundle/ruby/2.1.0/gems/rubocop-0.34.0/lib/rubocop/config_loader.rb:27:in `load_file'
/home/ubuntu/bundle/ruby/2.1.0/gems/rubocop-0.34.0/lib/rubocop/config_loader.rb:85:in `configuration_from_file'
/home/ubuntu/bundle/ruby/2.1.0/gems/rubocop-0.34.0/lib/rubocop/config_store.rb:40:in `for'
/home/ubuntu/bundle/ruby/2.1.0/gems/rubocop-0.34.0/lib/rubocop/target_finder.rb:112:in `excluded_dirs'
/home/ubuntu/bundle/ruby/2.1.0/gems/rubocop-0.34.0/lib/rubocop/target_finder.rb:90:in `find_files'
/home/ubuntu/bundle/ruby/2.1.0/gems/rubocop-0.34.0/lib/rubocop/target_finder.rb:60:in `target_files_in_dir'
/home/ubuntu/bundle/ruby/2.1.0/gems/rubocop-0.34.0/lib/rubocop/target_finder.rb:31:in `find'
/home/ubuntu/bundle/ruby/2.1.0/gems/rubocop-0.34.0/lib/rubocop/runner.rb:45:in `find_target_files'
/home/ubuntu/bundle/ruby/2.1.0/gems/rubocop-0.34.0/lib/rubocop/runner.rb:29:in `run'
/home/ubuntu/bundle/ruby/2.1.0/gems/rubocop-0.34.0/lib/rubocop/cli.rb:26:in `run'
/home/ubuntu/bundle/ruby/2.1.0/gems/rubocop-0.34.0/lib/rubocop/rake_task.rb:50:in `run_cli'
/home/ubuntu/bundle/ruby/2.1.0/gems/rubocop-0.34.0/lib/rubocop/rake_task.rb:38:in `run_main_task'
/home/ubuntu/bundle/ruby/2.1.0/gems/rubocop-0.34.0/lib/rubocop/rake_task.rb:30:in `block (2 levels) in initialize'
/home/ubuntu/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/file_utils_ext.rb:58:in `verbose'
/home/ubuntu/bundle/ruby/2.1.0/gems/rubocop-0.34.0/lib/rubocop/rake_task.rb:26:in `block in initialize'
/home/ubuntu/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/home/ubuntu/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/home/ubuntu/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/home/ubuntu/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/home/ubuntu/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/ubuntu/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/ubuntu/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/ubuntu/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/home/ubuntu/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
/home/ubuntu/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/home/ubuntu/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/home/ubuntu/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/ubuntu/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/ubuntu/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/home/ubuntu/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/home/ubuntu/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/ubuntu/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/home/ubuntu/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/home/ubuntu/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/home/ubuntu/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/home/ubuntu/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/home/ubuntu/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/ubuntu/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/home/ubuntu/bundle/ruby/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/home/ubuntu/bundle/ruby/2.1.0/bin/rake:23:in `load'
/home/ubuntu/bundle/ruby/2.1.0/bin/rake:23:in `<main>'

RuboCop failed! bundle exec rake style returned exit code 1
```

**Comment by kons4349** [comment]
Fixed in Rubocop 0.34.1
